- hosts: 127.0.0.1
  become_method: community.general.run0  # Ansible 2.21 has a problem with sudo-rs
  roles:
    - SecureDNS
    #- SSD
    #- Bash
    #- Git
    #- Chrome
    #- KeePass
    #- IDEA
    #- PhpStorm
    #- Docker
    #- workstation
  vars:
    user: dash
    home_dir: "/home/{{ user }}"
    git_email: 8299754+petrknap@users.noreply.github.com
    git_name: Petr Knap
