- name: Set required version
  set_fact:
    RestBreak:
      gist: 8c397e45dd5c39cc291f
      commit: 201962670cf6b123f6bc539fc7489a03a7fa8785

- name: Prepare directory
  file:
    path: "{{ home_dir }}/.apps/RestBreak"
    state: directory

- name: Download and install
  unarchive:
    src: "https://gist.github.com/petrknap/{{ RestBreak.gist }}/archive/{{ RestBreak.commit }}.zip"
    dest: "{{ home_dir }}/.apps/RestBreak"
    creates: "{{ home_dir }}/.apps/RestBreak/{{ RestBreak.gist }}-{{ RestBreak.commit }}"
    remote_src: yes

- name: Create desktop shortcut
  template:
    src: templates/RestBreak.desktop
    dest: "{{ home_dir }}/Desktop/RestBreak.desktop"
    mode: 0774
