# WARNING: Use it at the end of playlist

- name: Gather rules
  become: yes
  command: iptables-save
  register: rules

- name: Save rules
  become: yes
  copy:
    dest: /etc/iptables_rules
    content: "{{ rules.stdout }}"

- name: Restore rules on if-up
  become: yes
  copy:
    src: files/iptables-restore.bash
    dest: /etc/network/if-up.d/iptables-restore
    mode: 0555
