- name: Install other packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    force: yes
  with_items:
    - filezilla
    - git
    - gpg
    - make
    - mc
    - nano

- name: Generate locales
  become: yes
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items:
    - cs_CZ
    - cs_CZ.UTF-8

- name: Copy backup script
  copy:
    src: files/backup.bash
    dest: "{{ home_dir }}/backup.bash"
    mode: 0500

- name: Generate backup key
  shell: "#{{ lookup('password', home_dir + '/backup.key length=128') }}"

- name: Secure backup key
  file:
    path: "{{ home_dir }}/backup.key"
    mode: 0400

- name: Copy HP835G8.sleep script
  become: yes
  copy:
    src: files/hp835g8.sleep.bash
    dest: "/lib/systemd/system-sleep/hp835g8.sleep"
    mode: 0755
