- name: Set required version and build
  set_fact:
    PhpStorm:
      version: 2025.2.6.1
      build: 252.28539.57

- name: Prepare directory
  file:
    path: "{{ home_dir }}/.apps/PhpStorm"
    state: directory

- name: Download and install
  unarchive:
    src: "https://download.jetbrains.com/webide/PhpStorm-{{ PhpStorm.version }}.tar.gz"
    dest: "{{ home_dir }}/.apps/PhpStorm"
    creates: "{{ home_dir }}/.apps/PhpStorm/PhpStorm-{{ PhpStorm.build }}"
    remote_src: yes

- name: Create desktop shortcut
  template:
    src: templates/PhpStorm.desktop
    dest: "{{ home_dir }}/Desktop/PhpStorm.desktop"
    mode: 0774

- name: Set inotify watches limit # https://youtrack.jetbrains.com/articles/SUPPORT-A-1715/Inotify-Watches-Limit-Linux
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: 1048576
    state: present
