# https://linuxconfig.org/how-to-install-google-chrome-on-ubuntu-26-04#install-cli

- name: Check presence
  command: google-chrome --version
  register: chrome_check
  ignore_errors: yes

- name: Installation from .deb file
  when: chrome_check.rc != 0
  become: yes
  apt:
    state: present
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
