- name: Install needed packages
  become: yes
  apt:
    pkg:
      - docker.io
    state: present
    force: yes

- name: Check website.jar presence
  stat:
    path: "{{ directory }}/website.jar"
  register: website_jar

- fail:
    msg: "{{ directory }}/website.jar not found"
  when: website_jar.stat.exists == false

- name: Prepare directory
  become: yes
  file:
    path: "{{ directory }}"
    state: directory
    owner: "{{ user }}"

- name: Create config.json
  template:
    src: templates/config.json
    dest: "{{ directory }}/config.json"

- name: Copy files
  copy:
    src: "files/{{ item }}"
    dest: "{{ directory }}/{{ item }}"
  with_items:
    - accesses.bash
    - Dockerfile
    - .dockerignore

- name: Download JRE
  get_url:
    url: "https://download.bell-sw.com/java/21.0.7+9/bellsoft-jre21.0.7+9-linux-{{ architecture }}.deb"
    dest: "{{ directory }}/java.deb"

- name: Build image
  become: yes
  docker_image:
    path: "{{ directory }}/"
    name: petrknap/website
    tag: latest

- name: Start server
  become: yes
  docker_container:
    name: website
    image: petrknap/website:latest
    state: started
    restart: yes
    restart_policy: always
    volumes:
      - "{{ directory }}:/mnt/website"
    ports:
      - "{{ http_port }}:8080/tcp"
