- name: Check repository
  stat:
      path: /etc/apt/sources.list.d/docker.list
  register: repository

- fail:
    msg: Missing repository, see <https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository>
  when: not repository.stat.exists

- name: Uninstall all conflicting packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - containerd
    - docker-compose
    - docker-compose-v2
    - docker-doc
    - docker.io
    - podman-docker
    - runc

- name: Docker - install the latest version
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    force: yes
  with_items:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
