- name: Prevent disk cache to swap out existing apps from RAM # https://askubuntu.com/a/964933
  become: yes
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Prevent file searches to swap out existing apps from RAM # https://askubuntu.com/a/964933
  become: yes
  sysctl:
    name: vm.vfs_cache_pressure
    value: 50
    state: present

- name: Get root device UUID # https://serverfault.com/a/846188
  shell: cat /etc/fstab | grep "[^#].*\s/\s" | cut -d" " -f1 | cut -d"=" -f2
  register: root_uuid

- name: Set mount options for root device # https://serverfault.com/a/846188
  become: yes
  mount:
    path: /
    src: "UUID={{ root_uuid.stdout }}"
    fstype: ext4
    opts: "errors=remount-ro,noatime,nodiratime"
    passno: 1
    state: present
