name: Shell Linter

on:
  pull_request:
    paths:
      - '**.bash'
      - '**.sh'

jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: find . -name '*.bash' -or -name '*.sh' | xargs -tr shellcheck
